version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  run-dev:
    docker:
      - image: circleci/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: npm run webpack-start-dev
workflows:
  node-tests:
    jobs:
      - run-dev
      - node/test
