version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
jobs:
  spin-up-builds:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
          background: false
      - run:
          name: Run development server
          command: npm run webpack-start-dev
          background: true
      - run:
          name: Run production server
          command: npm run webpack-start-prod
          background: true
      - run:
          name: Run tests
          command: npm run test
          background: false
workflows:
  node-tests:
    jobs:
      - spin-up-builds
